{{- if not .Values.persistence.root.existingClaim }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "geoserver.fullname" . }}-root
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.root.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.root.size | quote }}
  {{- if .Values.persistence.root.storageClass }}
  storageClassName: {{ .Values.persistence.root.storageClass }}
  {{- end }}
{{- end }}
---
{{- if not .Values.persistence.coverages.existingClaim }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "geoserver.fullname" . }}-coverages
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.coverages.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.coverages.size | quote }}
  {{- if .Values.persistence.coverages.storageClass }}
  storageClassName: {{ .Values.persistence.coverages.storageClass }}
  {{- end }}
{{- end }}
---
{{- if not .Values.persistence.datadir.existingClaim }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "geoserver.fullname" . }}-datadir
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.datadir.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.datadir.size | quote }}
  {{- if .Values.persistence.datadir.storageClass }}
  storageClassName: {{ .Values.persistence.datadir.storageClass }}
  {{- end }}
{{- end }}
---
{{- if not .Values.persistence.memdumps.existingClaim }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "geoserver.fullname" . }}-memdumps
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.memdumps.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.memdumps.size | quote }}
  {{- if .Values.persistence.memdumps.storageClass }}
  storageClassName: {{ .Values.persistence.memdumps.storageClass }}
  {{- end }}
{{- end }}
---
{{- if and .Values.ingress.enabled (not .Values.persistence.postgis.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "geoserver.fullname" . }}-postgis
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.postgis.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.postgis.size | quote }}
  {{- if .Values.persistence.postgis.storageClass }}
  storageClassName: {{ .Values.persistence.postgis.storageClass }}
  {{- end }}
{{- end }}